- name: Install HAProxy
  yum:
    name: haproxy
    state: present

- name: Copy HAProxy config template
  template:
    src: haproxy.cfg2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Restart HAProxy
  systemd:
    name: haproxy
    state: restarted
    enabled: true
---
# tasks file for haproxy
