set nohlsearch
set number
set ignorecase
set smartcase
set incsearch
set hlsearch
set clipboard=unnamedplus
set laststatus=2
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent
set smarttab
set softtabstop=4
set showmatch
set ruler
set showcmd
set showmode
set backspace=indent,eol,start
set hidden
