---
- name: Install and configure HAProxy
  hosts: haproxy
  become: true
  tasks:
    - name: Install HAProxy
      yum:
        name: haproxy
        state: present

    - name: Copy HAProxy config file
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          global
              log /dev/log local0
              log /dev/log local1 notice
              daemon

          defaults
              log     global
              mode    http
              option  httplog
              timeout connect 5000
              timeout client  50000
              timeout server  50000

          frontend http_front
              bind *:8080
              default_backend http_back

          backend http_back
              balance roundrobin
              server web1 192.168.86.12:8080 check
              server web2 192.168.86.13:8080 check
              server web3 192.168.86.14:8080 check

    - name: Enable and start HAProxy
      systemd:
        name: haproxy
        state: started
        enabled: true

