- name: Set custom DNS resolver to dns01
  hosts: all:!dns
  become: true
  tasks:
    - name: Set nameserver to dns01 in /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver 192.168.86.22'
        state: present

