- hosts: docker_primary
  become: true
  tasks:
    - name: Initialize Docker swarm manager
      shell: docker swarm init --advertise-addr {{ ansible_host }}
      register: swarm_init
      failed_when: "'This node is already part of a swarm' not in swarm_init.stderr"

    - name: Get join token for workers
      shell: docker swarm join-token worker -q
      register: worker_token
      changed_when: false

    - name: Set worker join token fact
      set_fact:
        worker_token: "{{ worker_token.stdout }}"

