- name: Install and configure containerd (RHEL/CentOS)
  hosts: kubernetes
  become: true

  tasks:
    - name: Install required dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker CE repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install containerd
      yum:
        name: containerd.io
        state: present

    - name: Create default containerd config
      command: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Set Systemd as cgroup driver
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Enable and restart containerd
      systemd:
        name: containerd
        enabled: true
        state: restarted

