- name: Install Apache on Web Servers
  hosts: webservers
  become: true
  tasks:
    - name: Install Apache (httpd)
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is started and enabled
      service:
        name: httpd
        state: started
        enabled: true
