---
- name: Setup passwordless SSH for ansible user on all hosts
  hosts: all
  become: false
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Copy controller's SSH public key to remote authorized_keys
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

