---
- name: Update index.html uniquely on each web server
  hosts: webservers
  become: true

  tasks:
    - name: Set custom HTML content based on hostname
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Team3 Web Server</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      background-color: #222;
                      color: #fff;
                      text-align: center;
                      padding-top: 50px;
                  }
              </style>
          </head>
          <body>
              <h1>Welcome to Team3 - {{ inventory_hostname }}</h1>
              <p>Served by {{ ansible_hostname }}</p>
          </body>
          </html>
