---
- name: Initialize Kubernetes Master with kubeadm
  hosts: kubernetes
  become: true
  tasks:
    - name: Initialize the cluster
      command: >
        kubeadm init
        --apiserver-advertise-address={{ ansible_default_ipv4.address }}
        --pod-network-cidr=10.244.0.0/16
        --kubernetes-version=v1.29.15
        --ignore-preflight-errors=NumCPU
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory for root
      file:
        path: /root/.kube
        state: directory

    - name: Copy admin.conf to root kube config
      command: cp /etc/kubernetes/admin.conf /root/.kube/config

    - name: Set proper ownership for kube config
      file:
        path: /root/.kube/config
        owner: root
        group: root
        mode: '0600'

